version = 1
test_patterns = [
    "*.test.js",
    "*.spec.js"
]

[[analyzers]]
name = "test-coverage"
enabled = true

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "docker"
enabled = true
